name: moneyTI React CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Auth to GCP
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCE_SA_KEY }}
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v1
        with:
          working_directory: server
          project_id: ${{ secrets.GCP_PROJECT }}


      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moneyti-react .
          docker push ${{ secrets.DOCKER_USERNAME }}/moneyti-react:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_SSH_KEY }}
          script: |
            docker stop $(docker ps -a -q) 
            docker rm $(docker ps -a -q) 
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/moneyti-react:latest
            sudo docker tag ${{ secrets.DOCKER_USERNAME }}/moneyti-react:latest moneyti-react
            sudo docker run -d -p 3000:3000 joowojr/moneyti-react:latest
